project:
  type: website
  render:
    - "*.qmd"
  resources:
    - "/slides"

website:
  title: "PSYC 575 Multilevel Modeling (2022 Fall)"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Syllabus"
        file: syllabus.qmd
      - sidebar:modules
      - text: "R code"
        file: codes/rcode3.qmd
      - about.qmd

  sidebar:
    - id: modules
      title: "Modules"
      contents:
        - modules/week1.qmd
        - modules/week1b.qmd

    - title: "R code"
      contents:
        - codes/rcode3.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    df-print: paged



