project:
  type: website
  render:
    - "*.qmd"
    - "!/codes/rcode3.qmd"
  resources:
    - "/slides"
    - "!/slides/*.Rmd"

website:
  title: "PSYC 575 Multilevel Modeling (2022 Fall)"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Syllabus"
        file: syllabus.qmd
      - sidebar:modules
      - sidebar:codes

  sidebar:
    - id: modules
      title: "Modules"
      contents:
        - modules/week1.qmd
        - modules/week1b.qmd

    - id: codes
      title: "R code"
      contents:
        - codes/rcode1.qmd
        - codes/rcode1b.qmd
        # - codes/rcode3.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    df-print: paged



