project:
  type: website
  render:
    - "*.qmd"
  resources:
    - "/codes/*.Rmd"
    - "/slides"
    - "!/slides/*.Rmd"
    - "!/slides/slide_settings.RMarkdown"
    - "!/slides/img/cp_*"
    - "!/slides/*_cache/"
    - "!/slides/*.pptx"

website:
  title: "PSYC 575 Multilevel Modeling (2022 Fall)"
  google-analytics:
    tracking-id: "UA-225295148-1"
    storage: none
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Syllabus"
        file: syllabus.qmd
      - sidebar:modules
      - sidebar:codes

  sidebar:
    - id: modules
      title: "Modules"
      contents:
        - modules/week1.qmd
        - modules/week2.qmd
        - modules/week3.qmd
        - modules/week4.qmd
        - modules/week5.qmd
        - modules/week6.qmd
        - modules/week7.qmd

    - id: codes
      title: "R code"
      contents:
        - codes/rcode1.qmd
        - codes/rcode2.qmd
        - codes/rcode3.qmd
        - codes/rcode4.qmd
        - codes/rcode5.qmd
        - codes/rcode6.qmd
        - codes/rcode7.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    df-print: paged



